#!/bin/env python3

import argparse
import sys
import textwrap

def main():
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("name")
    arg_parser.add_argument("input", type=argparse.FileType("rb"))
    arg_parser.add_argument("output", type=argparse.FileType("wt"))

    args = arg_parser.parse_args()

    file = args.output
    file.write(textwrap.dedent("""\
        // This file was automatically generated by embed_resource.py
        // Do not edit!

        #include "Resource.hpp"

        namespace cobbletext {

        """))

    file.write("const uint8_t Resource::{name}[] {{\n".format(name=args.name))

    while True:
        data = args.input.read(20)

        if len(data) == 0:
            break

        file.write("    ")

        for byte in data:
            file.write(str(byte))
            file.write(", ")

        file.write("\n")

    file.write("};\n")

    file.write("const size_t Resource::{name}_SIZE = {size};\n\n".format(
        name=args.name, size=args.input.tell()))

    file.write(textwrap.dedent("""\

        }
        """))

if __name__ == "__main__":
    main()
