name: CI

on: [push, pull_request]

jobs:
  build_test_build_release:
    strategy:
      fail-fast: false
      matrix:
        target: [windows-x86, windows-x64, ubuntu, macos]
        include:
          # We're using static linking on Windows for the tests
          # because it uses C++ API which is not properly supported yet
          - target: windows-x86
            vm: windows-latest
            triplet: x86-windows
            cmake_platform_flag: "-A Win32"
            test_link_static: "true"
            test_build_type: Debug
            release_build_flag: "--config Release"
          - target: windows-x64
            vm: windows-latest
            triplet: x64-windows
            cmake_platform_flag: "-A x64"
            test_link_static: "true"
            test_build_type: Debug
            release_build_flag: "--config Release"
          - target: ubuntu
            vm: ubuntu-latest
            triplet: x64-linux-dynamic-release # freetype won't link bz2 correctly with vcpkg debug
            cmake_platform_flag: ""
            test_link_static: "false"
            test_build_type: Release # can't use debug because vcpkg toolchain links debug libs
            release_build_flag: ""
          - target: macos
            vm: macos-latest
            triplet: x64-osx-dynamic-release # libicudata doesn't get built or link properly with vcpkg debug
            cmake_platform_flag: ""
            test_link_static: "false"
            test_build_type: Release # same reason above
            release_build_flag: ""
    runs-on: ${{ matrix.vm }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: true
      # Install our C/C++ library dependencies
      # and test support libraries:
      - uses: actions/cache@v1
        id: cache-vcpkg
        with:
          key: vcpkg-${{ matrix.target }}-v2
          path: vcpkg/
      - run: |
          mkdir -p ./vcpkg
          cp -a $VCPKG_INSTALLATION_ROOT/. ./vcpkg/
          ./vcpkg/vcpkg install \
            --triplet ${{ matrix.triplet }} \
            --overlay-triplets=misc/vcpkg_custom_triplets \
            freetype[png] harfbuzz[ucdn] icu ms-gsl catch2 \
            boost-container-hash
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      - uses: actions/cache@v1
        id: cache-uthash
        with:
          key: uthash-${{ matrix.target }}-v1
          path: lib/uthash/
      - run: |
          cd lib
          git clone https://github.com/troydhanson/uthash.git
          cd uthash
          git checkout 1124f0a70b0714886402c3c0df03d037e3c4d57a
        if: steps.cache-uthash.outputs.cache-hit != 'true'
      # Build in debug mode for testing:
      - run: |
          mkdir build
          cd build
          cmake .. -D CMAKE_BUILD_TYPE=${{ matrix.test_build_type }} ${{ matrix.cmake_platform_flag }} \
            -D CMAKE_VERBOSE_MAKEFILE=true \
            -D COBBLETEXT_BUILD_DOCS=false \
            -D COBBLETEXT_STATIC=${{ matrix.test_link_static }} \
            -D VCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
            -D CMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -D UTHASH_INCLUDE_PATH=$GITHUB_WORKSPACE/lib/uthash/src/
      - run: |
          cmake --build . --target test_main
          cmake --build . --target ppm_example
        working-directory: build/
      - run: ctest --verbose -C Debug
        working-directory: build/
      # Now build dynamic library:
      - run: |
          mkdir build-release
          cd build-release
          cmake .. -D CMAKE_BUILD_TYPE=Release ${{ matrix.cmake_platform_flag }} \
            -D CMAKE_VERBOSE_MAKEFILE=true \
            -D COBBLETEXT_BUILD_DOCS=false \
            -D COBBLETEXT_BUILD_TESTS=false \
            -D COBBLETEXT_BUILD_EXAMPLES=false \
            -D VCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
            -D CMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake
      - run: |
          cmake --build . --target cobbletext ${{ matrix.release_build_flag }}
        working-directory: build-release/
      - uses: actions/upload-artifact@v1
        with:
          name: bin-${{ matrix.triplet }}
          path: build-release/bin/
      - run: |
          rm -f ./vcpkg/vcpkg-export* \
          ./vcpkg/vcpkg export \
            --triplet ${{ matrix.triplet }} \
            --overlay-triplets=misc/vcpkg_custom_triplets \
            --7zip \
            freetype[png] harfbuzz[ucdn] icu
      - run: |
          mkdir -p build-release/bin-dependencies/ \
          mv ./vcpkg/vcpkg-export* build-release/bin-dependencies/
      - uses: actions/upload-artifact@v1
        with:
          name: bin-dependencies-${{ matrix.triplet }}
          path: build-release/bin-dependencies/
